# Generated by Django 4.2.6 on 2023-10-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email2', models.EmailField(max_length=254, unique=True)),
                ('password2', models.CharField(max_length=100)),
            ],
        ),
    ]
