# Generated by Django 4.2.6 on 2023-10-31 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_credentials2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials',
            new_name='Credential',
        ),
        migrations.RenameModel(
            old_name='Credentials2',
            new_name='Credential2',
        ),
    ]
