# Generated by Django 4.2.6 on 2023-10-31 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_credentials_credential_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credential2',
        ),
    ]
